spring.application.name=ApiGateway
server.port=4544

spring.cloud.gateway.server.webmvc.routes[0].id=QuizService
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://QUIZSERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/quiz/**

spring.cloud.gateway.server.webmvc.routes[1].id=QuestionService
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://QUESTIONSERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/question/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
